### ISSUE TITLE
Prevent BikePoint mutations

### ISSUE THREAD

**Issue by RossWilliams** [gsans/amplify-london-bikes#1]
Without any auth rules, someone can easily move bike points, delete them, or deface the name with offensive text. Mutation auth rules should be added

**Comment by gsans** [comment]
How is that going to happen? There are no users. Besides, that's not possible as API access remains secured via API key and there's no UI to do that. 

Anyway, in the current design, there is no need for user registration/login. BikePoints are only for admin purposes to update bike stations over time as the service changes.

**Comment by RossWilliams** [comment]
The API key is public and embedded in the javascript code. The solution deploys a graphql introspection endpoint to see all mutations that are available, all these mutations are available to use with the API key.

If I understand you, you are saying that the frontend UI is where the API is being protected. I don't think this follows the spirit of security as job #1.

With the endpoint and public API key, i can delete all existing bike endpoints and create my own:

<img width="482" alt="Screenshot 2020-05-25 at 17 59 27" src="https://user-images.githubusercontent.com/1443442/82831953-bb7aab00-9eb1-11ea-96c9-e3548398ae67.png">

**Comment by gsans** [comment]
Sure. I appreciate your concerns.

As I was saying, this is supposed to be an admin API. If you are worried
about these issues you should totally add extra security measures before
using in production.

This is out of the scope for this project.

**Comment by gsans** [comment]
Closing
